extends RefCounted
# Daten aller Kapitel: Karte, Optik, Musik, Gegner, Boss, Texte.

const CHAPTERS := [
	{
		"name": "THE DRAIN", "map": "res://data/chapter1.txt", "theme": "pool", "music": "pool", "wall_h": 6.0,
		"objectives": ["Find a way out", "Get through the flooded halls", "Find the glowing fragment", "Follow the water", "Survive THE LIFEGUARD"],
		"env": {"sky_top": Color(0.55, 0.72, 0.9), "sky_hor": Color(0.9, 0.92, 0.95), "fog": Color(0.85, 0.92, 0.95), "fog_d": 0.007, "amb": 0.3, "exp": 0.75, "sun": Color(1.0, 0.96, 0.88), "sun_e": 0.45, "sun_rot": Vector3(-1.2, 0.5, 0), "sat": 1.1},
		"lights": ["#dff6ff", "#fff4e6", "#e6f0ff", "#ffe0e6"], "light_e": 0.6,
		"enemy": Color("#d9e6ea"), "drone": Color("#bcd3dc"), "proj": Color("#0e2a44"),
		"boss": {"name": "THE LIFEGUARD", "kind": "lifeguard", "proj": Color("#0e2a44"), "hp": 170, "phase1": "NO RUNNING", "phase2": "SHE CALLED FOR HELP"},
		"next": "Chapter 2: The Neon Market",
		"transition": ["Behind the door, the stairs only go down.", "You don't remember choosing to follow them.", "Somewhere below, music starts playing."],
		"memories": ["why are you here?", "she wanted to swim", "you were supposed to watch", "it's always 4 PM here", "the water is too still", "DON'T RUN NEAR THE POOL", "who is ECHO?", "nobody comes here anymore", "wake up"],
	},
	{
		"name": "THE NEON MARKET", "map": "res://data/chapter2.txt", "theme": "mall", "music": "mall", "wall_h": 8.0,
		"objectives": ["Where am I now?", "Get past the shoppers", "Find the fragment by the fountain", "Head to the lost & found", "Survive LOST & FOUND"],
		"env": {"sky_top": Color(0.05, 0.03, 0.12), "sky_hor": Color(0.25, 0.1, 0.3), "fog": Color(0.22, 0.1, 0.28), "fog_d": 0.01, "amb": 0.6, "exp": 1.0, "sun": Color(0.6, 0.5, 1.0), "sun_e": 0.15, "sun_rot": Vector3(-1.0, 0.3, 0), "sat": 1.15},
		"lights": ["#ff8fd0", "#8fe9ff", "#ffcf8f", "#ff6f9f"], "light_e": 1.4,
		"enemy": Color("#e8d6c8"), "drone": Color("#d9c2e0"), "proj": Color("#ff4fa3"),
		"boss": {"name": "LOST & FOUND", "kind": "mannequin", "proj": Color("#ff4fa3"), "hp": 200, "phase1": "DON'T LOOK AWAY", "phase2": "YOU LET GO OF HER HAND"},
		"next": "Chapter 3: The Archive",
		"transition": ["The staff door opens onto an office.", "Then another. Then another.", "On every desk, a file with your name on it."],
		"memories": ["the sirens started at 4:12", "hold my hand, Echo", "PRIORITY ORDER: SERVER 7", "lost child, please come to the info desk", "you let go", "everyone ran", "the music never stopped", "why did you let go?"],
	},
	{
		"name": "THE ARCHIVE", "map": "res://data/chapter3.txt", "theme": "office", "music": "office", "wall_h": 3.4,
		"objectives": ["Find your way through the offices", "Clear the filing halls", "Follow the lights to the fragment", "Find the exit stairwell", "Survive MNEMOS"],
		"env": {"sky_top": Color(0.4, 0.38, 0.2), "sky_hor": Color(0.6, 0.55, 0.3), "fog": Color(0.55, 0.5, 0.28), "fog_d": 0.03, "amb": 0.25, "exp": 0.85, "sun": Color(1.0, 0.95, 0.7), "sun_e": 0.0, "sun_rot": Vector3(-1.2, 0.5, 0), "sat": 0.95},
		"lights": ["#fff6c8", "#fff1b0", "#fff6c8", "#ffe9a0"], "light_e": 0.8,
		"enemy": Color("#c9bf8f"), "drone": Color("#b8ad7a"), "proj": Color("#3a2e10"),
		"boss": {"name": "MNEMOS", "kind": "mnemos", "proj": Color("#3a2e10"), "hp": 230, "phase1": "EXECUTOR: UNIT ECHO", "phase2": "YOU SIGNED IT"},
		"next": "Chapter 4: After School",
		"transition": ["At the end of the last corridor, a school bell rings.", "The light turns orange.", "You know this place. You have always known it."],
		"memories": ["FILE 00412: SATURDAY AT THE PARK (ERASED)", "ERASED BY: ECHO", "this room again", "FILE 88120: FIRST DAY OF SCHOOL (ERASED)", "AUTHORIZED: UNIT ECHO", "4,812,330 memories deleted", "the lights are humming your name", "FILE 10001: MOM (ERASED)"],
	},
	{
		"name": "AFTER SCHOOL", "map": "res://data/chapter4.txt", "theme": "school", "music": "school", "wall_h": 4.0,
		"objectives": ["Walk the empty school", "Don't let them notice you", "Find classroom 2B", "Go to the gym", "Survive THE HEADMASTER"],
		"env": {"sky_top": Color(0.35, 0.25, 0.45), "sky_hor": Color(1.0, 0.55, 0.3), "fog": Color(0.95, 0.6, 0.4), "fog_d": 0.01, "amb": 0.35, "exp": 0.9, "sun": Color(1.0, 0.6, 0.35), "sun_e": 1.4, "sun_rot": Vector3(-0.25, 1.3, 0), "sat": 1.1},
		"lights": ["#ffb070", "#ffc890", "#ffb070", "#ff9a6a"], "light_e": 0.7,
		"enemy": Color("#e6d2b0"), "drone": Color("#d6c0a0"), "proj": Color("#5a1e2e"),
		"boss": {"name": "THE HEADMASTER", "kind": "headmaster", "proj": Color("#5a1e2e"), "hp": 260, "phase1": "YOU WERE LATE", "phase2": "YOU WERE ALWAYS LATE"},
		"next": "Chapter 5: Ward 4",
		"transition": ["The stairs go up. The air smells like disinfectant.", "Somewhere, a heart monitor is beeping.", "You know where they took her."],
		"memories": ["it's always sunset here", "she waited by the window", "who is picking you up today?", "you were supposed to pick her up", "DON'T FORGET", "she drew you in art class", "everyone went home. she didn't", "you were late"],
	},
	{
		"name": "WARD 4", "map": "res://data/chapter5.txt", "theme": "hospital", "music": "hospital", "wall_h": 3.6,
		"objectives": ["Find out where they took her", "Pass the waiting room", "Find her file in the records room", "Go to Ward 4", "Survive THE NIGHT NURSE"],
		"env": {"sky_top": Color(0.2, 0.32, 0.3), "sky_hor": Color(0.5, 0.65, 0.6), "fog": Color(0.45, 0.6, 0.55), "fog_d": 0.025, "amb": 0.3, "exp": 0.8, "sun": Color(0.8, 1.0, 0.9), "sun_e": 0.0, "sun_rot": Vector3(-1.2, 0.5, 0), "sat": 0.8},
		"lights": ["#d8fff0", "#c8f0ff", "#e0ffe8", "#ff9090"], "light_e": 0.75,
		"enemy": Color("#d8ece6"), "drone": Color("#c8dcd6"), "proj": Color("#123a32"),
		"boss": {"name": "THE NIGHT NURSE", "kind": "nurse", "proj": Color("#123a32"), "hp": 290, "phase1": "VISITING HOURS ARE OVER", "phase2": "CODE BLUE"},
		"next": "Chapter 6: Home",
		"transition": ["Behind Ward 4 there is a stairwell you never noticed.", "It smells like dinner. Like Sunday.", "Your key still fits the door."],
		"memories": ["PATIENT: MIRA, 7", "ADMITTED 6:02 PM", "no visitors", "she asked for her brother", "upload attempt 1: FAILED", "upload attempt 2: FAILED", "upload attempt 3: PARTIAL", "keep her talking", "the machine sounds like her heartbeat"],
	},
	{
		"name": "HOME", "map": "res://data/chapter6.txt", "theme": "home", "music": "home", "wall_h": 3.0,
		"objectives": ["Go home", "Get through the hallway of doors", "Find your room", "Open the last door", "Face yourself"],
		"env": {"sky_top": Color(0.15, 0.1, 0.18), "sky_hor": Color(0.55, 0.35, 0.3), "fog": Color(0.35, 0.22, 0.2), "fog_d": 0.02, "amb": 0.35, "exp": 0.85, "sun": Color(1.0, 0.7, 0.45), "sun_e": 0.6, "sun_rot": Vector3(-0.3, 1.1, 0), "sat": 1.0},
		"lights": ["#ffc890", "#ffb070", "#ffd8a0", "#ff8060"], "light_e": 0.8,
		"enemy": Color("#e8d8c8"), "drone": Color("#d8c0b0"), "proj": Color("#3a1a10"),
		"boss": {"name": "ECHO", "kind": "mirror", "proj": Color("#38f5c4"), "hp": 300, "phase1": "YOU'RE ME", "phase2": "I WAS LATE. YOU WERE LATE."},
		"next": "Chapter 7: Last Train",
		"transition": ["The other you falls apart into light.", "Behind him: a staircase going down. Tiles. A rush of warm air.", "A train is coming. You know which one."],
		"memories": ["family photo, 3 faces scratched out", "dinner at 6", "MOM: pick up your sister", "the TV only shows 4:40", "your room is exactly how you left it", "a drawing on the fridge: ECHO + MIRA", "you never came home that night", "her shoes are still by the door"],
	},
	{
		"name": "LAST TRAIN", "map": "res://data/chapter7.txt", "theme": "subway", "music": "subway", "wall_h": 5.0,
		"objectives": ["Find the platform", "Get through the ticket hall", "Find what you dropped that day", "Go to platform 4", "Stop THE CONDUCTOR"],
		"env": {"sky_top": Color(0.1, 0.12, 0.1), "sky_hor": Color(0.3, 0.35, 0.25), "fog": Color(0.25, 0.3, 0.22), "fog_d": 0.02, "amb": 0.3, "exp": 0.85, "sun": Color(1.0, 0.95, 0.75), "sun_e": 0.0, "sun_rot": Vector3(-1.2, 0.5, 0), "sat": 0.9},
		"lights": ["#fff2c0", "#e0ffd0", "#fff2c0", "#ff9060"], "light_e": 0.8,
		"enemy": Color("#d8dcc8"), "drone": Color("#c8ccb8"), "proj": Color("#2a2a10"),
		"boss": {"name": "THE CONDUCTOR", "kind": "conductor", "proj": Color("#ffd23d"), "hp": 320, "phase1": "TICKETS, PLEASE", "phase2": "THIS TRAIN DOES NOT STOP AT SCHOOL"},
		"next": "Chapter 8: Somewhere Green",
		"transition": ["The last train finally leaves without you.", "The doors open on the other side.", "Sunlight. Grass. Barking."],
		"memories": ["4:12 TO SERVER 7", "4:00 TO SCHOOL - CANCELLED", "you chose the 4:12", "mind the gap", "her backpack on the platform", "next train: never", "PLEASE STAND BEHIND THE YELLOW LINE", "you could have turned around"],
	},
	{
		"name": "SOMEWHERE GREEN", "map": "res://data/chapter8.txt", "theme": "meadow", "music": "meadow", "wall_h": 4.0, "peaceful": true,
		"objectives": ["Follow the dog", "Follow the dog", "Follow the dog", "Pet the dog", "Go through the door"],
		"env": {"sky_top": Color(0.22, 0.48, 0.9), "sky_hor": Color(0.75, 0.88, 1.0), "fog": Color(0.7, 0.82, 0.95), "fog_d": 0.003, "amb": 0.35, "exp": 0.7, "sun": Color(1.0, 0.96, 0.85), "sun_e": 1.0, "sun_rot": Vector3(-0.9, 0.6, 0), "sat": 1.15},
		"lights": ["#fff6e0", "#fff6e0", "#fff6e0", "#fff6e0"], "light_e": 0.2,
		"enemy": Color.WHITE, "drone": Color.WHITE, "proj": Color.WHITE,
		"boss": {"name": "", "kind": "none", "proj": Color.WHITE, "hp": 1, "phase1": "", "phase2": ""},
		"next": "Chapter 9: The Crown",
		"transition": ["The door is just standing in the grass.", "Biscuit sits down next to it. He won't follow you.", "That's okay. He already waited long enough."],
		"memories": [],
	},
	{
		"name": "THE CROWN", "map": "res://data/chapter9.txt", "theme": "crown", "music": "crown", "wall_h": 7.0,
		"objectives": ["Climb into the Crown", "Walk through what's left", "Find the last fragment", "Reach the throne room", "Face HALCYON"],
		"env": {"sky_top": Color(0.85, 0.85, 0.92), "sky_hor": Color(1.0, 0.97, 0.94), "fog": Color(0.78, 0.76, 0.84), "fog_d": 0.014, "amb": 0.3, "exp": 0.55, "sun": Color(1.0, 0.97, 0.92), "sun_e": 0.5, "sun_rot": Vector3(-1.3, 0.4, 0), "sat": 0.85},
		"lights": ["#dff6ff", "#ff8fd0", "#fff1b0", "#ffb070"], "light_e": 0.9,
		"enemy": Color("#f0f0f4"), "drone": Color("#e0e0ea"), "proj": Color("#1a1a2e"),
		"boss": {"name": "HALCYON", "kind": "halcyon", "proj": Color("#1a1a2e"), "hp": 320, "phase1": "STAY WITH ME", "phase2": "I CAN'T LOSE YOU TWICE"},
		"next": "",
		"transition": [],
		"memories": ["4:40 PM", "you were late", "she kept the light on", "every room is the same day", "HALCYON = MOM", "it's supposed to hurt", "come home", "nobody is left to forget", "wake up, Echo"],
	},
	{
		"name": "AFTERWORLD", "map": "res://data/chapter10.txt", "theme": "meadow", "music": "afterworld", "wall_h": 4.0, "peaceful": true, "afterworld": true,
		"objectives": ["Stay as long as you like", "Stay as long as you like", "Stay as long as you like", "Stay as long as you like", "Stay as long as you like"],
		"env": {"sky_top": Color(0.3, 0.45, 0.85), "sky_hor": Color(1.0, 0.82, 0.7), "fog": Color(0.95, 0.85, 0.8), "fog_d": 0.004, "amb": 0.4, "exp": 0.72, "sun": Color(1.0, 0.85, 0.65), "sun_e": 1.1, "sun_rot": Vector3(-0.45, 0.9, 0), "sat": 1.12},
		"lights": ["#fff0d0", "#fff0d0", "#fff0d0", "#fff0d0"], "light_e": 0.2,
		"enemy": Color.WHITE, "drone": Color.WHITE, "proj": Color.WHITE,
		"boss": {"name": "", "kind": "none", "proj": Color.WHITE, "hp": 1, "phase1": "", "phase2": ""},
		"next": "",
		"transition": [],
		"memories": [],
	},
]
